<?php
// $Id: location.pe.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Peru

function location_province_list_pe() {
  return array('AM' => "Amazonas",
    'AN' => "Ancash",
    'AP' => "Apurimac",
    'AR' => "Arequipa",
    'AY' => "Ayacucho",
    'CJ' => "Cajamarca",
    'CL' => "Callao",
    'CU' => "Cusco",
    'HV' => "Huancavelica",
    'HO' => "Huanuco",
    'IC' => "Ica",
    'JU' => "Junin",
    'LD' => "La Libertad",
    'LY' => "Lambayeque",
    'LI' => "Lima",
    'LO' => "Loreto",
    'MD' => "Madre de Dios",
    'MO' => "Moquegua",
    'PA' => "Pasco",
    'PI' => "Piura",
    'PU' => "Puno",
    'SM' => "San Martin",
    'TA' => "Tacna",
    'TU' => "Tumbes",
    'UC' => "Ucayali");
}
