<?php
// $Id: location.rw.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Rwanda

function location_province_list_rw() {
  return array('BU' => "Butare",
    'BY' => "Byumba",
    'CY' => "Cyangugu",
    'GK' => "Gikongoro",
    'GS' => "Gisenyi",
    'GT' => "Gitarama",
    'KG' => "Kibungo",
    'KY' => "Kibuye",
    'KR' => "Kigali Rurale",
    'KV' => "Kigali-ville",
    'RU' => "Ruhengeri",
    'UM' => "Umutara");
}
