<?php
// $Id: location.la.inc,v 1.6.4.1 2009/02/04 20:04:10 bdragon Exp $

// Lao People's Democratic Republic

function location_province_list_la() {
  return array('VT' => "Vientiane",
    'AT' => "Attapu",
    'BK' => "Bokeo",
    'BL' => "Bolikhamxai",
    'CH' => "Champasak",
    'HO' => "Houaphan",
    'KH' => "Khammouan",
    'LM' => "Louang Namtha",
    'LP' => "Louangphabang",
    'OU' => "Oudomxai",
    'PH' => "Phongsali",
    'SL' => "Salavan",
    'SV' => "Savannakhet",
    'VI' => "Vientiane",
    'XA' => "Xaignabouli",
    'XE' => "Xekong",
    'XI' => "Xiangkhoang",
    'XN' => "Xaisomboun");
}
