<?php
// $Id: location.tl.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Timor Leste

function location_province_list_tl() {
  return array('AL' => "Aileu",
    'AN' => "Ainaro",
    'BA' => "Baucau",
    'BO' => "Bobonaro",
    'CO' => "Cova Lima",
    'DI' => "Dili",
    'ER' => "Ermera",
    'LA' => "Lautem",
    'LI' => "Liquica",
    'MT' => "Manatuto",
    'MF' => "Manufahi",
    'OE' => "Oecussi",
    'VI' => "Viqueque");
}
