<?php
// $Id: location.mm.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Myanmar

function location_province_list_mm() {
  return array('AY' => "Ayeyarwady",
    'BG' => "Bago",
    'MG' => "Magway",
    'MD' => "Mandalay",
    'SG' => "Sagaing",
    'TN' => "Tanintharyi",
    'YG' => "Yangon",
    'CH' => "Chin State",
    'KC' => "Kachin State",
    'KH' => "Kayah State",
    'KN' => "Kayin State",
    'MN' => "Mon State",
    'RK' => "Rakhine State",
    'SH' => "Shan State");
}
