<?php
// $Id: location.bb.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Barbados

function location_province_list_bb() {
  return array('CC' => "Christ Church",
    'AND' => "Saint Andrew",
    'GEO' => "Saint George",
    'JAM' => "Saint James",
    'JOH' => "Saint John",
    'JOS' => "Saint Joseph",
    'LUC' => "Saint Lucy",
    'MIC' => "Saint Michael",
    'PET' => "Saint Peter",
    'PHI' => "Saint Philip",
    'THO' => "Saint Thomas");
}
