<?php
// $Id: location.am.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Armenia

function location_province_list_am() {
  return array('AGT' => "Aragatsotn",
    'ARR' => "Ararat",
    'ARM' => "Armavir",
    'GEG' => "Geghark'unik'",
    'KOT' => "Kotayk'",
    'LOR' => "Lorri",
    'SHI' => "Shirak",
    'SYU' => "Syunik'",
    'TAV' => "Tavush",
    'VAY' => "Vayots' Dzor",
    'YER' => "Yerevan");
}
