<?php
// $Id: location.ar.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Argentina

function location_province_list_ar() {
  return array('A' => "Salta",
    'B' => "Buenos Aires Province",
    'C' => "Distrito Federal",
    'D' => "San Luis",
    'E' => "Entre Rios",
    'F' => "La Rioja",
    'G' => "Santiago del Estero",
    'H' => "Chaco",
    'J' => "San Juan",
    'K' => "Catamarca",
    'L' => "La Pampa",
    'M' => "Mendoza",
    'N' => "Misiones",
    'P' => "Formosa",
    'Q' => "Neuquen",
    'R' => "Rio Negro",
    'S' => "Santa Fe",
    'T' => "Tucuman",
    'U' => "Chubut",
    'V' => "Tierra del Fuego",
    'W' => "Corrientes",
    'X' => "Cordoba",
    'Y' => "Jujuy",
    'Z' => "Santa Cruz");
}
