<?php
// $Id: location.tt.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Trinidad and Tobago

function location_province_list_tt() {
  return array('CT' => "Couva/Tabaquite/Talparo",
    'DM' => "Diego Martin",
    'MR' => "Mayaro/Rio Claro",
    'PD' => "Penal/Debe",
    'PT' => "Princes Town",
    'SG' => "Sangre Grande",
    'SL' => "San Juan/Laventille",
    'SI' => "Siparia",
    'TP' => "Tunapuna/Piarco",
    'PS' => "Port of Spain",
    'SF' => "San Fernando",
    'AR' => "Arima",
    'PF' => "Point Fortin",
    'CH' => "Chaguanas",
    'TO' => "Tobago");
}
