<?php
// $Id: location.nz.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// New Zealand

function location_province_list_nz() {
  return array('AUK' => "Auckland",
    'BOP' => "Bay of Plenty",
    'CAN' => "Canterbury",
    'GIS' => "Gisborne",
    'HKB' => "Hawke's Bay",
    'MBH' => "Marlborough",
    'MWT' => "Manawatu-Wanganui",
    'NSN' => "Nelson",
    'NTL' => "Northland",
    'OTA' => "Otago",
    'STL' => "Southland",
    'TAS' => "Tasman",
    'TKI' => "Taranaki",
    'WGN' => "Wellington",
    'WKO' => "Waikato",
    'WTC' => "West Coast");
}
