<?php
// $Id: location.et.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Ethiopia

function location_province_list_et() {
  return array('AF' => "Afar",
    'AH' => "Amhara",
    'BG' => "Benishangul-Gumaz",
    'GB' => "Gambela",
    'HR' => "Hariai",
    'OR' => "Oromia",
    'SM' => "Somali",
    'SN' => "Southern Nations - Nationalities and Peoples Region",
    'TG' => "Tigray",
    'AA' => "Addis Ababa",
    'DD' => "Dire Dawa");
}
