<?php
// $Id $

// Sweden

function location_province_list_se() {
  return array('ST' => "Stockholm",
    'UP' => "Uppsala",
    'SO' => "Södermanland",
    'OG' => "Östergotland",
    'JO' => "Jönköping",
    'KR' => "Kronoberg",
    'KA' => "Kalmar",
    'GO' => "Gotland",
    'BL' => "Blekinge",
    'SK' => "Skåne",
    'HA' => "Halland",
    'VG' => "Västra Götaland",
    'VL' => "Värmland",
    'OR' => "Örebro",
    'VM' => "Västmanland",
    'DA' => "Dalarna",
    'GA' => "Gävleborg",
    'VN' => "Västernorrland",
    'JA' => "Jämtland",
    'VB' => "Västerbotten",
    'NO' => "Norrbotten");
}
