<?php
// $Id: location.kh.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Cambodia

function location_province_list_kh() {
  return array('PP' => "Phnom Penh",
    'PS' => "Preah Seihanu (Kompong Som or Sihanoukville)",
    'PA' => "Pailin",
    'KB' => "Keb",
    'BM' => "Banteay Meanchey",
    'BA' => "Battambang",
    'KM' => "Kampong Cham",
    'KN' => "Kampong Chhnang",
    'KU' => "Kampong Speu",
    'KO' => "Kampong Som",
    'KT' => "Kampong Thom",
    'KP' => "Kampot",
    'KL' => "Kandal",
    'KK' => "Kaoh Kong",
    'KR' => "Kratie",
    'MK' => "Mondul Kiri",
    'OM' => "Oddar Meancheay",
    'PU' => "Pursat",
    'PR' => "Preah Vihear",
    'PG' => "Prey Veng",
    'RK' => "Ratanak Kiri",
    'SI' => "Siemreap",
    'ST' => "Stung Treng",
    'SR' => "Svay Rieng",
    'TK' => "Takeo");
}
