<?php
// $Id: location.vn.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Vietnam

function location_province_list_vn() {
  return array('AG' => "An Giang",
    'BG' => "Bac Giang",
    'BK' => "Bac Kan",
    'BL' => "Bac Lieu",
    'BC' => "Bac Ninh",
    'BR' => "Ba Ria-Vung Tau",
    'BN' => "Ben Tre",
    'BH' => "Binh Dinh",
    'BU' => "Binh Duong",
    'BP' => "Binh Phuoc",
    'BT' => "Binh Thuan",
    'CM' => "Ca Mau",
    'CT' => "Can Tho",
    'CB' => "Cao Bang",
    'DL' => "Dak Lak",
    'DG' => "Dak Nong",
    'DN' => "Da Nang",
    'DB' => "Dien Bien",
    'DI' => "Dong Nai",
    'DT' => "Dong Thap",
    'GL' => "Gia Lai",
    'HG' => "Ha Giang",
    'HD' => "Hai Duong",
    'HP' => "Hai Phong",
    'HM' => "Ha Nam",
    'HI' => "Ha Noi",
    'HT' => "Ha Tay",
    'HH' => "Ha Tinh",
    'HB' => "Hoa Binh",
    'HC' => "Ho Chin Minh",
    'HU' => "Hau Giang",
    'HY' => "Hung Yen");
}
