<?php
// $Id: location.bo.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Bolivia

function location_province_list_bo() {
  return array('BEN' => "Departmento Beni",
    'CHU' => "Departmento Chuquisaca",
    'COC' => "Departmento Cochabamba",
    'LPZ' => "Departmento La Paz",
    'ORU' => "Departmento Oruro",
    'PAN' => "Departmento Pando",
    'POT' => "Departmento Potosi",
    'SCZ' => "Departmento Santa Cruz",
    'TAR' => "Departmento Tarija");
}
