<?php
// $Id: location.af.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Afghanistan

function location_province_list_af() {
  return array('BDS' => "Badakhshan province",
    'BDG' => "Badghis province",
    'BGL' => "Baghlan province",
    'BAL' => "Balkh province",
    'BAM' => "Bamian province",
    'FRA' => "Farah province",
    'FYB' => "Faryab province",
    'GHA' => "Ghazni province",
    'GHO' => "Ghowr province",
    'HEL' => "Helmand province",
    'HER' => "Herat province",
    'JOW' => "Jowzjan province",
    'KAB' => "Kabul province",
    'KAN' => "Kandahar province",
    'KAP' => "Kapisa province",
    'KHO' => "Khost province",
    'KNR' => "Konar province",
    'KDZ' => "Kondoz province",
    'LAG' => "Laghman province",
    'LOW' => "Lowgar province",
    'NAN' => "Nangrahar province",
    'NIM' => "Nimruz province",
    'NUR' => "Nurestan province",
    'ORU' => "Oruzgan province",
    'PIA' => "Paktia province",
    'PKA' => "Paktika province",
    'PAR' => "Parwan province",
    'SAM' => "Samangan province",
    'SAR' => "Sar-e Pol province",
    'TAK' => "Takhar province",
    'WAR' => "Wardak province",
    'ZAB' => "Zabol province");
}
