<?php
// $Id: location.kr.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Korea, Republic Of (South Korea)

function location_province_list_kr() {
  return array('11' => "Seoul Special City",
    '26' => "Busan Metropolitan City",
    '27' => "Daegu Metropolitan City",
    '28' => "Incheon Metropolitan City",
    '29' => "Gwangju Metropolitan City",
    '30' => "Daejeon Metropolitan City",
    '31' => "Ulsan Metropolitan City",
    '41' => "Gyeonggi-do",
    '42' => "Gangwon-do",
    '43' => "Chungcheongbuk-do",
    '44' => "Chungcheongnam-do",
    '45' => "Jeollabuk-do",
    '46' => "Jeollanam-do",
    '47' => "Gyeongsangbuk-do",
    '48' => "Gyeongsangnam-do",
    '49' => "Jeju-do");
}
