<?php
// $Id: location.bi.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Burundi

function location_province_list_bi() {
  return array('BB' => "Bubanza",
    'BJ' => "Bujumbura",
    'BR' => "Bururi",
    'CA' => "Cankuzo",
    'CI' => "Cibitoke",
    'GI' => "Gitega",
    'KR' => "Karuzi",
    'KY' => "Kayanza",
    'KI' => "Kirundo",
    'MA' => "Makamba",
    'MU' => "Muramvya",
    'MY' => "Muyinga",
    'MW' => "Mwaro",
    'NG' => "Ngozi",
    'RT' => "Rutana",
    'RY' => "Ruyigi");
}
