<?php
// $Id: location.hk.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Hong Kong

function location_province_list_hk() {
  return array('HCW' => "Central and Western Hong Kong Island",
    'HEA' => "Eastern Hong Kong Island",
    'HSO' => "Southern Hong Kong Island",
    'HWC' => "Wan Chai Hong Kong Island",
    'KKC' => "Kowloon City Kowloon",
    'KKT' => "Kwun Tong Kowloon",
    'KSS' => "Sham Shui Po Kowloon",
    'KWT' => "Wong Tai Sin Kowloon",
    'KYT' => "Yau Tsim Mong Kowloon",
    'NIS' => "Islands New Territories",
    'NKT' => "Kwai Tsing New Territories",
    'NNO' => "North New Territories",
    'NSK' => "Sai Kung New Territories",
    'NST' => "Sha Tin New Territories",
    'NTP' => "Tai Po New Territories",
    'NTW' => "Tsuen Wan New Territories",
    'NTM' => "Tuen Mun New Territories",
    'NYL' => "Yuen Long New Territories");
}
