<?php
// $Id: location.py.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Paraguay

function location_province_list_py() {
  return array('AG' => "Alto Paraguay",
    'AN' => "Alto Parana",
    'AM' => "Amambay",
    'AS' => "Asuncion",
    'BO' => "Boqueron",
    'CG' => "Caaguazu",
    'CZ' => "Caazapa",
    'CN' => "Canindeyu",
    'CE' => "Central",
    'CC' => "Concepcion",
    'CD' => "Cordillera",
    'GU' => "Guaira",
    'IT' => "Itapua",
    'MI' => "Misiones",
    'NE' => "Neembucu",
    'PA' => "Paraguari",
    'PH' => "Presidente Hayes",
    'SP' => "San Pedro");
}
