<?php
// $Id: location.pl.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Poland

function location_province_list_pl() {
  return array('DO' => "Dolnoslaskie",
    'KP' => "Kujawsko-Pomorskie",
    'LO' => "Lodzkie",
    'LL' => "Lubelskie",
    'LU' => "Lubuskie",
    'ML' => "Malopolskie",
    'MZ' => "Mazowieckie",
    'OP' => "Opolskie",
    'PP' => "Podkarpackie",
    'PL' => "Podlaskie",
    'PM' => "Pomorskie",
    'SL' => "Slaskie",
    'SW' => "Swietokrzyskie",
    'WM' => "Warminsko-Mazurskie",
    'WP' => "Wielkopolskie",
    'ZA' => "Zachodniopomorskie");
}
