<?php
// $Id: location.my.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Malaysia

function location_province_list_my() {
  return array('JH' => "Johor",
    'KD' => "Kedah",
    'KN' => "Kelantan",
    'KL' => "Kuala Lumpur",
    'ML' => "Malacca",
    'NS' => "Negeri Sembilan",
    'PH' => "Pahang",
    'PK' => "Perak",
    'PS' => "Perlis",
    'PG' => "Penang",
    'WP' => "Wilayah Persekutuan",
    'SL' => "Selangor",
    'TR' => "Terengganu",
    'LB' => "Labuan",
    'SB' => "Sabah",
    'SR' => "Sarawak");
}
