<?php
// $Id: location.mv.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Maldives

function location_province_list_mv() {
  return array('THU' => "Thiladhunmathi Uthuru",
    'THD' => "Thiladhunmathi Dhekunu",
    'MLU' => "Miladhunmadulu Uthuru",
    'MLD' => "Miladhunmadulu Dhekunu",
    'MAU' => "Maalhosmadulu Uthuru",
    'MAD' => "Maalhosmadulu Dhekunu",
    'FAA' => "Faadhippolhu",
    'MAA' => "Male Atoll",
    'AAU' => "Ari Atoll Uthuru",
    'AAD' => "Ari Atoll Dheknu",
    'FEA' => "Felidhe Atoll",
    'MUA' => "Mulaku Atoll",
    'NAU' => "Nilandhe Atoll Uthuru",
    'NAD' => "Nilandhe Atoll Dhekunu",
    'KLH' => "Kolhumadulu",
    'HDH' => "Hadhdhunmathi",
    'HAU' => "Huvadhu Atoll Uthuru",
    'HAD' => "Huvadhu Atoll Dhekunu",
    'FMU' => "Fua Mulaku",
    'ADD' => "Addu");
}
