<?php
// $Id: location.hn.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Honduras

function location_province_list_hn() {
  return array('AT' => "Atlantida",
    'CH' => "Choluteca",
    'CL' => "Colon",
    'CM' => "Comayagua",
    'CP' => "Copan",
    'CR' => "Cortes",
    'PA' => "El Paraiso",
    'FM' => "Francisco Morazan",
    'GD' => "Gracias a Dios",
    'IN' => "Intibuca",
    'IB' => "Islas de la Bahia (Bay Islands)",
    'PZ' => "La Paz",
    'LE' => "Lempira",
    'OC' => "Ocotepeque",
    'OL' => "Olancho",
    'SB' => "Santa Barbara",
    'VA' => "Valle",
    'YO' => "Yoro");
}
