<?php
// $Id: location.ly.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Libyan Arab Jamahiriya

function location_province_list_ly() {
  return array('AJ' => "Ajdabiya",
    'AZ' => "Al 'Aziziyah",
    'FA' => "Al Fatih",
    'JA' => "Al Jabal al Akhdar",
    'JU' => "Al Jufrah",
    'KH' => "Al Khums",
    'KU' => "Al Kufrah",
    'NK' => "An Nuqat al Khams",
    'AS' => "Ash Shati'",
    'AW' => "Awbari",
    'ZA' => "Az Zawiyah",
    'BA' => "Banghazi",
    'DA' => "Darnah",
    'GD' => "Ghadamis",
    'GY' => "Gharyan",
    'MI' => "Misratah",
    'MZ' => "Murzuq",
    'SB' => "Sabha",
    'SW' => "Sawfajjin",
    'SU' => "Surt",
    'TL' => "Tarabulus (Tripoli)",
    'TH' => "Tarhunah",
    'TU' => "Tubruq",
    'YA' => "Yafran",
    'ZL' => "Zlitan");
}
