<?php
// $Id: location.cz.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Czech Republic

function location_province_list_cz() {
  return array('JC' => "South Bohemian Region (Jihocesky kraj)",
    'JM' => "South Moravian Region (Jihomoravsky kraj)",
    'KA' => "Carlsbad Region  (Karlovarsky kraj)",
    'VY' => "Vysoc(ina Region (kraj Vysoc(ina)",
    'KR' => "Hradec Kralove Region (Kralovehradecky kraj)",
    'LI' => "Liberec Region (Liberecky kraj)",
    'MO' => "Moravian-Silesian Region (Moravskoslezsky kraj)",
    'OL' => "Olomouc Region (Olomoucky kraj)",
    'PA' => "Pardubice Region (Pardubicky kraj)",
    'PL' => "Plzen( Region Plzensky kraj)",
    'PR' => "Prague - the Capital (Praha - hlavni mesto)",
    'ST' => "Central Bohemian Region (Stredocesky kraj)",
    'US' => "Usti nad Labem Region (Ustecky kraj)",
    'ZL' => "Zlin Region (Zlinsky kraj)");
}
