<?php
// $Id: location.td.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Chad

function location_province_list_td() {
  return array('BA' => "Batha",
    'BI' => "Biltine",
    'BE' => "Borkou-Ennedi-Tibesti",
    'CB' => "Chari-Baguirmi",
    'GU' => "Guera",
    'KA' => "Kanem",
    'LA' => "Lac",
    'LC' => "Logone Occidental",
    'LR' => "Logone Oriental",
    'MK' => "Mayo-Kebbi",
    'MC' => "Moyen-Chari",
    'OU' => "Ouaddai",
    'SA' => "Salamat",
    'TA' => "Tandjile");
}
