<?php
// $Id: location.bj.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Benin

function location_province_list_bj() {
  return array('AL' => "Alibori",
    'AK' => "Atakora",
    'AQ' => "Atlantique",
    'BO' => "Borgou",
    'CO' => "Collines",
    'DO' => "Donga",
    'KO' => "Kouffo",
    'LI' => "Littoral",
    'MO' => "Mono",
    'OU' => "Oueme",
    'PL' => "Plateau",
    'ZO' => "Zou");
}
