<?php
// $Id: location.bt.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Bhutan

function location_province_list_bt() {
  return array('BUM' => "Bumthang",
    'CHU' => "Chukha",
    'DAG' => "Dagana",
    'GAS' => "Gasa",
    'HAA' => "Haa",
    'LHU' => "Lhuntse",
    'MON' => "Mongar",
    'PAR' => "Paro",
    'PEM' => "Pemagatshel",
    'PUN' => "Punakha",
    'SJO' => "Samdrup Jongkhar",
    'SAT' => "Samtse",
    'SAR' => "Sarpang",
    'THI' => "Thimphu",
    'TRG' => "Trashigang",
    'TRY' => "Trashiyangste",
    'TRO' => "Trongsa",
    'TSI' => "Tsirang",
    'WPH' => "Wangdue Phodrang",
    'ZHE' => "Zhemgang");
}
