<?php
// $Id: location.ie.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Ireland

function location_province_list_ie() {
  return array('DB' => "Dublin",
    'WK' => "Wicklow",
    'WX' => "Wexford",
    'CW' => "Carlow",
    'KD' => "Kildare",
    'MT' => "Meath",
    'LT' => "Louth",
    'MG' => "Monaghan",
    'CV' => "Cavan",
    'LF' => "Longford",
    'WM' => "Westmeath",
    'OF' => "Offaly",
    'LA' => "Laois",
    'KK' => "Kilkenny",
    'WF' => "Waterford",
    'CK' => "Cork",
    'KR' => "Kerry",
    'LM' => "Limerick",
    'TP' => "Tipperary",
    'CL' => "Clare",
    'GW' => "Galway",
    'MY' => "Mayo",
    'RC' => "Roscommon",
    'SL' => "Sligo",
    'LR' => "Leitrim",
    'DG' => "Donegal");
}
