<?php
// $Id: location.cv.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Cape Verde

function location_province_list_cv() {
  return array('BV' => "Boa Vista",
    'BR' => "Brava",
    'CS' => "Calheta de Sao Miguel",
    'MA' => "Maio",
    'MO' => "Mosteiros",
    'PA' => "Paul",
    'PN' => "Porto Novo",
    'PR' => "Praia",
    'RG' => "Ribeira Grande",
    'SL' => "Sal",
    'CA' => "Santa Catarina",
    'CR' => "Santa Cruz",
    'SD' => "Sao Domingos",
    'SF' => "Sao Filipe",
    'SN' => "Sao Nicolau",
    'SV' => "Sao Vicente",
    'TA' => "Tarrafal");
}
