<?php

/* Implementation of hook_menu(); */
function menuxml_menu($may_cache) {
  global $user;
  $items = array();
  $items[] = array('path' => 'menu-xml-export', 'title' => t('Menu XML export'), 'access' => TRUE, 'type' => MENU_CALLBACK, 'callback' => 'generate_menu_xml');
  return $items;
}

function generate_menu_xml() {
  $menu = menu_get_menu();
  print_r($menu);

  if (isset($menu['visible'][$pid]) && $menu['visible'][$pid]['children']) {
    foreach ($menu['visible'][$pid]['children'] as $mid) {
      $type = isset($menu['visible'][$mid]['type']) ? $menu['visible'][$mid]['type'] : NULL;
      $children = isset($menu['visible'][$mid]['children']) ? $menu['visible'][$mid]['children'] : NULL;
//      $XMLOUTPUT = // tady se bude generovat XML
    }
  }
  echo $XMLOUTPUT;
}
