<?php
// $Id: location.jm.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Jamaica

function location_province_list_jm() {
  return array('CLA' => "Clarendon Parish",
    'HAN' => "Hanover Parish",
    'KIN' => "Kingston Parish",
    'MAN' => "Manchester Parish",
    'POR' => "Portland Parish",
    'AND' => "Saint Andrew Parish",
    'ANN' => "Saint Ann Parish",
    'CAT' => "Saint Catherine Parish",
    'ELI' => "Saint Elizabeth Parish",
    'JAM' => "Saint James Parish",
    'MAR' => "Saint Mary Parish",
    'THO' => "Saint Thomas Parish",
    'TRL' => "Trelawny Parish",
    'WML' => "Westmoreland Parish");
}
