<?php
// $Id: location.mh.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Marshall Islands

function location_province_list_mh() {
  return array('ALG' => "Ailinginae",
    'ALL' => "Ailinglaplap",
    'ALK' => "Ailuk",
    'ARN' => "Arno",
    'AUR' => "Aur",
    'BKR' => "Bikar",
    'BKN' => "Bikini",
    'BKK' => "Bokak",
    'EBN' => "Ebon",
    'ENT' => "Enewetak",
    'EKB' => "Erikub",
    'JBT' => "Jabat",
    'JLT' => "Jaluit",
    'JEM' => "Jemo",
    'KIL' => "Kili",
    'KWJ' => "Kwajalein",
    'LAE' => "Lae",
    'LIB' => "Lib",
    'LKP' => "Likiep",
    'MJR' => "Majuro",
    'MLP' => "Maloelap",
    'MJT' => "Mejit",
    'MIL' => "Mili",
    'NMK' => "Namorik",
    'NAM' => "Namu",
    'RGL' => "Rongelap",
    'RGK' => "Rongrik",
    'TOK' => "Toke",
    'UJA' => "Ujae",
    'UJL' => "Ujelang",
    'UTK' => "Utirik",
    'WTH' => "Wotho",
    'WTJ' => "Wotje");
}
