<?php
// $Id: location.ba.inc,v 1.6 2008/01/24 09:00:02 bdragon Exp $

// Bosnia and Herzegovina

function location_province_list_ba() {
  return array('BRO' => "Brcko district",
    'FUS' => "Unsko-Sanski Kanton",
    'FPO' => "Posavski Kanton",
    'FTU' => "Tuzlanski Kanton",
    'FZE' => "Zenicko-Dobojski Kanton",
    'FBP' => "Bosanskopodrinjski Kanton",
    'FSB' => "Srednjebosanski Kanton",
    'FHN' => "Hercegovacko-neretvanski Kanton",
    'FZH' => "Zapadnohercegovacka Zupanija",
    'FSA' => "Kanton Sarajevo",
    'FZA' => "Zapadnobosanska",
    'SBL' => "Banja Luka",
    'SDO' => "Doboj",
    'SBI' => "Bijeljina",
    'SVL' => "Vlasenica",
    'SSR' => "Sarajevo-Romanija or Sokolac",
    'SFO' => "Foca",
    'STR' => "Trebinje");
}
