<?php
// $Id: location.tc.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Turks and Caicos Islands

function location_province_list_tc() {
  return array('AC' => "Ambergris Cays",
    'DC' => "Dellis Cay",
    'FC' => "French Cay",
    'LW' => "Little Water Cay",
    'RC' => "Parrot Cay",
    'PN' => "Pine Cay",
    'SL' => "Salt Cay",
    'GT' => "Grand Turk",
    'SC' => "South Caicos",
    'EC' => "East Caicos",
    'MC' => "Middle Caicos",
    'NC' => "North Caicos",
    'PR' => "Providenciales",
    'WC' => "West Caicos");
}
