<?php
// $Id: location.pw.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Palau

function location_province_list_pw() {
  return array('AM' => "Aimeliik",
    'AR' => "Airai",
    'AN' => "Angaur",
    'HA' => "Hatohobei",
    'KA' => "Kayangel",
    'KO' => "Koror",
    'ME' => "Melekeok",
    'NA' => "Ngaraard",
    'NG' => "Ngarchelong",
    'ND' => "Ngardmau",
    'NT' => "Ngatpang",
    'NC' => "Ngchesar",
    'NR' => "Ngeremlengui",
    'NW' => "Ngiwal",
    'PE' => "Peleliu",
    'SO' => "Sonsorol");
}
