<?php
// $Id: location.np.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Nepal

function location_province_list_np() {
  return array('BA' => "Bagmati",
    'BH' => "Bheri",
    'DH' => "Dhawalagiri",
    'GA' => "Gandaki",
    'JA' => "Janakpur",
    'KA' => "Karnali",
    'KO' => "Kosi",
    'LU' => "Lumbini",
    'MA' => "Mahakali",
    'ME' => "Mechi",
    'NA' => "Narayani",
    'RA' => "Rapti",
    'SA' => "Sagarmatha",
    'SE' => "Seti");
}
