<?php
// $Id: location.ni.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Nicaragua

function location_province_list_ni() {
  return array('BO' => "Boaco",
    'CA' => "Carazo",
    'CD' => "Chinandega",
    'CT' => "Chontales",
    'ES' => "Esteli",
    'GR' => "Granada",
    'JI' => "Jinotega",
    'LE' => "Leon",
    'MD' => "Madriz",
    'MN' => "Managua",
    'MS' => "Masaya",
    'MT' => "Matagalpa",
    'NS' => "Nueva Segovia",
    'RV' => "Rivas",
    'SJ' => "Rio San Juan",
    'AN' => "Region Autonoma del Atlantico Norte",
    'AS' => "Region Autonoma del Atlantico Sur");
}
