<?php
// $Id: location.gn.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Guinea

function location_province_list_gn() {
  return array('CNK' => "Conakry",
    'BYL' => "Beyla",
    'BFA' => "Boffa",
    'BOK' => "Boke",
    'COY' => "Coyah",
    'DBL' => "Dabola",
    'DLB' => "Dalaba",
    'DGR' => "Dinguiraye",
    'DBR' => "Dubreka",
    'FRN' => "Faranah",
    'FRC' => "Forecariah",
    'FRI' => "Fria",
    'GAO' => "Gaoual",
    'GCD' => "Gueckedou",
    'KNK' => "Kankan",
    'KRN' => "Kerouane",
    'KND' => "Kindia",
    'KSD' => "Kissidougou",
    'KBA' => "Koubia",
    'KDA' => "Koundara",
    'KRA' => "Kouroussa",
    'LAB' => "Labe",
    'LLM' => "Lelouma",
    'LOL' => "Lola",
    'MCT' => "Macenta",
    'MAL' => "Mali",
    'MAM' => "Mamou",
    'MAN' => "Mandiana",
    'NZR' => "Nzerekore",
    'PIT' => "Pita",
    'SIG' => "Siguiri",
    'TLM' => "Telimele",
    'TOG' => "Tougue",
    'YOM' => "Yomou");
}
