<?php
// $Id: location.mn.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Mongolia

function location_province_list_mn() {
  return array('1' => "Ulanbaatar",
    '035' => "Orhon",
    '037' => "Darhan uul",
    '039' => "Hentiy",
    '041' => "Hovsgol",
    '043' => "Hovd",
    '046' => "Uvs",
    '047' => "Tov",
    '049' => "Selenge",
    '051' => "Suhbaatar",
    '053' => "Omnogovi",
    '055' => "Ovorhangay",
    '057' => "Dzavhan",
    '059' => "DundgovL",
    '061' => "Dornod",
    '063' => "Dornogov",
    '064' => "Govi-Sumber",
    '065' => "Govi-Altay",
    '067' => "Bulgan",
    '069' => "Bayanhongor",
    '071' => "Bayan-Olgiy",
    '073' => "Arhangay");
}
