<?php
// $Id: location.tn.inc,v 1.6 2008/01/24 09:00:03 bdragon Exp $

// Tunisia

function location_province_list_tn() {
  return array('AR' => "Ariana",
    'BJ' => "Beja",
    'BA' => "Ben Arous",
    'BI' => "Bizerte",
    'GB' => "Gabes",
    'GF' => "Gafsa",
    'JE' => "Jendouba",
    'KR' => "Kairouan",
    'KS' => "Kasserine",
    'KB' => "Kebili",
    'KF' => "Kef",
    'MH' => "Mahdia",
    'MN' => "Manouba",
    'ME' => "Medenine",
    'MO' => "Monastir",
    'NA' => "Nabeul",
    'SF' => "Sfax",
    'SD' => "Sidi",
    'SL' => "Siliana",
    'SO' => "Sousse",
    'TA' => "Tataouine",
    'TO' => "Tozeur",
    'TU' => "Tunis",
    'ZA' => "Zaghouan");
}
