<?php

/**
  * Implementation of hook_mail_alter().
  * TODO d.cz redesign: This doesn't belong here.
  */
function katalogwebu_mail_alter(&$message) {
  if ($message['mailkey'] == 'signup_forwarding_mail'  || $message['mailkey'] == 'signup_confirmation_mail') {
    $message['body'] = 'Děkujeme za registraci na akci. Těšíme se na Vás.';
  }
} 

/**
  * Implementation of hook_form_alter().
  */
function katalogwebu_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_register') {
    $form['Osobní informace']['#collapsible'] = TRUE;
    $form['Osobní informace']['#collapsed'] = TRUE;
  }
  if ($form_id == 'user_edit') {
    $form['comment_settings']['signature']['#type'] = 'hidden';
  }
}

/**
  * Implementation of hook_menu().
  */
function katalogwebu_menu() {
      $items['katalog'] = array('title' => 'Katalog webů v Drupalu',
          'page callback' => 'katalog_display',
          'access arguments' => array('access content'),
          'type' => MENU_CALLBACK,
          );
    return $items;
}

function katalog_display() {

  if ($term = arg(2)) {
    // Find a term for this view.
    require_once drupal_get_path('module', 'pathauto').'/pathauto.inc';
    $res = db_query("SELECT * FROM {term_data} WHERE vid = 10 OR vid = 9");
    while ($row = db_fetch_array($res)) {
      $cleanterm = pathauto_cleanstring($row['name']);
      if ($term === $cleanterm) {
        $tid = $row['tid'];
        break;
      }
    }
    if (!$tid) {
      drupal_not_found(); exit;
    }
  }

  $content = '<p class="katalog-text">Toto je katalog českých webů postavených na Drupalu. Katalog je členěn do kategorií, nebo-li tagů, každý záznam může být v několika kategoriích. Přesvěčte se sami, že Drupal není jen hračka, ale seriózní systém! <a href="/node/add/content-katalog">Přidat záznam do katalogu</a>.</p>';


  // Show tags only if term not found.
  if ($tid) {
    $view = views_embed_view('katalogwebu', 'default', $tid);
  } else {
    $view = views_embed_view('katalogwebu', 'default');
  }


  $tags = tagadelic_block('view', '10');
  $tagadelic = '<div class="katalog-tags">' . $tags['content'] . '</div>';

  return $content . $tagadelic . $view;
}
